### ISSUE TITLE
利用規約かライセンスについて

### ISSUE THREAD

**Issue by yukieiji** [hinakkyu/TheOtherHats#1]
READMEには「他MODでも使っていただけると大変嬉しい」と記載されていますが利用規約制限は無いとのことでしょうか
また、OSSのライセンス(MITとかApache)でもあれば他のMODでも使いやすいと思います

ライセンスや利用規約的に問題がなければ私のMODのExtreme Skins側での実装を予定しています(利用規約やライセンスも同時に付けて使用します)

**Comment by hinakkyu** [comment]
お問い合わせありがとうございます。
以下の3点をご了承いただけるのであれば、本スキンを使っていただければと思います。
・第三者への誹謗中傷行為に使用することを禁止
・自作発言の禁止
・本スキンの使用によって生じる一切の請求、損害、
　その他の義務について責任を負いません

規約等は整えますので、お時間をください。
※ReadMeに追記します。

**Comment by yukieiji** [comment]
利用規約等はReadMeより別ファイル(LICENSE.mdが一般的)に記載していいただけるとすごい嬉しいです(コピペミスによる記載忘れや改変しにくいですし、リンクを貼って誰でも確認しやすい)

**Comment by hinakkyu** [comment]
大変お待たせしました。
LICENSE.md を追加しました。

**Comment by yukieiji** [comment]
追加ありがとうございます

以下の点を確認したいです
- MODによっては読み込みの関係上ファイル名やデータ構造等を変更する必要があります、その場合このスキンのデータを別リポジトリ(このリポジトリのLICENCE.mdの付与も行います)にアップロードしてもよろしいでしょうか(再配布になるはずです)
- スキン製作者の名前も記載したいのですが「Hachiman」、「hinaniki」、「mement」とそれぞれ日本語だとどのような名前がよろしいでしょうか

**Comment by hinakkyu** [comment]
＞MODによっては読み込みの関係上ファイル名やデータ構造等を変更する必要があります、
＞その場合このスキンのデータを別リポジトリ(このリポジトリのLICENCE.mdの付与も行います)に
＞アップロードしてもよろしいでしょうか(再配布になるはずです)
再配布について、LICENCE.mdにQ＆A項目を追加しました。
また別リポジトリのアップロードも規約内の使用であれば問題ありません。

＞スキン製作者の名前も記載したいのですが
＞「Hachiman」、「hinaniki」、「mement」と
＞それぞれ日本語だとどのような名前がよろしいでしょうか
下記の通りにお願いします。
「Hachiman」⇒八幡宮
「hinaniki」⇒ひなにい
「mement」⇒めめんともり
「mizore」⇒みぞれ

**Comment by yukieiji** [comment]
> 再配布について、LICENCE.mdにQ＆A項目を追加しました。
また別リポジトリのアップロードも規約内の使用であれば問題ありません。

承知しました

> 下記の通りにお願いします。
「Hachiman」⇒八幡宮
「hinaniki」⇒ひなにい
「mement」⇒めめんともり
「mizore」⇒みぞれ

翻訳も完了してExtreme Skinsへの実装と公開を行いました
確認していただき翻訳等のミスがなければこのままクローズします

**Comment by hinakkyu** [comment]
確認しました。問題ありません。

**Comment by yukieiji** [comment]
お時間を頂いて確認とスキンの実装許可、ありがとうございます
クローズさせていただきます
